<?php


use App\Models\User;
use Carbon\Carbon;

class UserTest extends TestCase
{
    protected User $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = new User([
            'lastname' => 'dfzefz',
            'firstname' => 'fdszfez',
            'uncrypted_password' => 'ezfezddzzddd',
            'email' => 'tao.berquer@gmail.com',
            'birthday' => new Carbon('07/03/1999')
        ]);
    }

    public function testIsValidNominal()
    {
        $this->assertEmpty($this->user->isValid());
    }

    public function testNotValideDueToLastname()
    {
        $this->user->lastname = null;
        $this->assertNotEmpty($this->user->isValid());
    }

    public function testNotValideDueToFirstname()
    {
        $this->user->firstname = null;
        $this->assertNotEmpty($this->user->isValid());
    }

    public function testNotValideDueToPassword()
    {
        $this->user->uncrypted_password = '5454';
        $this->assertNotEmpty($this->user->isValid());
        $this->user->uncrypted_password = 'a6eRqjj^HuGgNjeTFrz!4Ws!^7KM5b6Zw#6m@9VG4';
        $this->assertNotEmpty($this->user->isValid());
    }

    public function testNotValideDueToEmail()
    {
        $this->user->email = 'dddd.com';
        $this->assertNotEmpty($this->user->isValid());
    }

    public function testNotValideDueToBirthday()
    {
        $this->user->birthday = Carbon::now()->subYear('1');
        $this->assertNotEmpty($this->user->isValid());
    }
}
