name: PHPUnit

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: user
          MYSQL_PASSWORD: user
          MYSQL_DATABASE: dbname

    steps:
      - uses: actions/checkout@v2
      - name: Laravel Setup
        run: |
          cp .env.ci .env
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: dbname
          DB_PORT: 3306
          DB_USER: user
          DB_PASSWORD: user
        run: |
          php artisan migrate
          vendor/phpunit/phpunit/phpunit
